DROP TABLE IF EXISTS verification;

CREATE TABLE verification (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	email TEXT NOT NULL,
	key TEXT NOT NULL
);
